version: '3.7'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: circleci/rabbitmq-delayed:3.7.23-management-31
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: postgres
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  rabbitmq_data:
    external: true
    name: dev_stack_rabbitmq_data
  mongodb_data:
    external: true
    name: dev_stack_mongodb_data
  postgresdb_data:
    external: true
    name: dev_stack_postgresdb_data
# docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=500m,uid=1000 dev_stack_postgresdb_data
