version: '3.1'
services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: root
    volumes:
      - mongodb_data:/data/db
  rabbitmq:
    image: circleci/rabbitmq-delayed:3.7.23-management-31
    ports:
      - 15672
      - 5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 5672:5672
      - 15672:15672
      - 27017:27017
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
volumes:
  rabbitmq_data:
    external: true
    name: dev_stack_rabbitmq_data
  mongodb_data:
    external: true
    name: dev_stack_mongodb_data

# docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=500m,uid=1000 dev_stack_rabbitmq_data
